---
- name: Viki test playbook
  hosts: localhost
  #become: true
  #become_method: sudo
  vars:
      #repository_url: git@github.com:valet2you/DemoGitTest.git
      #repository_path: /var/www/html
      #key_file: /root/.ssh/id_rsa.github
      #project_name: viki-devops-test
      files_dir: /home/vpandey/test_playbooks/files/
  tasks:
    - name: Check if a file exist
      stat:
        path: "{{ files_dir }}test.txt"
      register: settingsfile
    - debug:
            msg: "file mode is {{ settingsfile.stat.mode }}"
    - acl: 
        name: "{{ files_dir }}test.txt"
      register: settingsfile_orig_acl
    - debug:
            msg: "The File exists and acl is {{ settingsfile_orig_acl.acl }}"
      when: "{{ settingsfile.stat.exists }}"
    - file:
        path: "{{ files_dir }}test.txt"
        state: touch
        mode: "0777"
    - acl:
        name: "{{ files_dir }}test.txt"
      register: settingsfile_modified_acl
    - debug:
            msg: "{{ settingsfile_modified_acl['acl'] }}"
    - file: 
        path: "{{ files_dir }}test.txt"
        state: touch
        mode: "{{ settingsfile.stat.mode }}"
        
